begin;

create table if not exists public.ranking_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid not null,
  player_name text not null,
  score integer not null,
  accuracy numeric(5, 2) not null,
  wpm numeric(6, 2) not null,
  problems_solved smallint not null,
  best_combo smallint not null,
  survival_ms integer not null,
  game_mode text not null,
  content_version text not null,
  client_version text not null,
  created_at timestamptz not null default now(),

  constraint ranking_entries_user_session_key unique (user_id, session_id),
  constraint ranking_entries_player_name_check
    check (player_name ~ '^[가-힣A-Za-z0-9_]{2,12}$'),
  constraint ranking_entries_score_check check (score between 0 and 10000000),
  constraint ranking_entries_accuracy_check check (accuracy between 0 and 100),
  constraint ranking_entries_wpm_check check (wpm between 0 and 250),
  constraint ranking_entries_problems_check check (problems_solved between 1 and 40),
  constraint ranking_entries_combo_check check (best_combo between 0 and 40),
  constraint ranking_entries_survival_check check (survival_ms between 10000 and 300000),
  constraint ranking_entries_mode_check check (game_mode = 'quick'),
  constraint ranking_entries_content_version_check
    check (
      char_length(content_version) between 1 and 20
      and content_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$'
    ),
  constraint ranking_entries_client_version_check
    check (
      char_length(client_version) between 1 and 20
      and client_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$'
    )
);

create index if not exists ranking_entries_global_idx
  on public.ranking_entries
  (
    content_version,
    game_mode,
    score desc,
    accuracy desc,
    problems_solved desc,
    best_combo desc,
    wpm desc,
    created_at asc
  );

create index if not exists ranking_entries_user_idx
  on public.ranking_entries
  (
    user_id,
    content_version,
    game_mode,
    score desc,
    accuracy desc,
    problems_solved desc,
    best_combo desc,
    wpm desc,
    created_at asc
  );

create index if not exists ranking_entries_today_idx
  on public.ranking_entries (created_at desc, content_version, game_mode);

alter table public.ranking_entries enable row level security;

drop policy if exists "Leaderboard is readable" on public.ranking_entries;
create policy "Leaderboard is readable"
on public.ranking_entries
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated anonymous users insert own runs"
  on public.ranking_entries;
create policy "Authenticated anonymous users insert own runs"
on public.ranking_entries
for insert
to authenticated
with check ((select auth.uid()) = user_id);

-- The browser has no raw-table SELECT privilege. Public reads go through the
-- narrow RPC return types below so user_id/session_id are never returned.
revoke all on table public.ranking_entries from public, anon, authenticated;
grant insert (
  user_id,
  session_id,
  player_name,
  score,
  accuracy,
  wpm,
  problems_solved,
  best_combo,
  survival_ms,
  game_mode,
  content_version,
  client_version
) on public.ranking_entries to authenticated;

-- created_at and id are intentionally omitted from the INSERT grant. They can
-- only be assigned by PostgreSQL, not backdated or chosen by a browser client.
revoke all on sequence public.ranking_entries_id_seq from public, anon, authenticated;
grant usage on sequence public.ranking_entries_id_seq to authenticated;

create or replace function public.get_global_ranking(
  p_content_version text,
  p_limit integer default 100
)
returns table (
  rank bigint,
  player_name text,
  score integer,
  accuracy numeric(5, 2),
  wpm numeric(6, 2),
  problems_solved smallint,
  best_combo smallint,
  survival_ms integer,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if p_limit is null or p_limit < 1 or p_limit > 100 then
    raise exception 'limit must be between 1 and 100' using errcode = '22023';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;

  return query
  with per_user as (
    select
      entry.*,
      row_number() over (
        partition by entry.user_id
        order by
          entry.score desc,
          entry.accuracy desc,
          entry.problems_solved desc,
          entry.best_combo desc,
          entry.wpm desc,
          entry.created_at asc,
          entry.id asc
      ) as user_position
    from public.ranking_entries as entry
    where entry.content_version = p_content_version
      and entry.game_mode = 'quick'
  ),
  ranked as (
    select
      row_number() over (
        order by
          candidate.score desc,
          candidate.accuracy desc,
          candidate.problems_solved desc,
          candidate.best_combo desc,
          candidate.wpm desc,
          candidate.created_at asc,
          candidate.id asc
      ) as entry_rank,
      candidate.*
    from per_user as candidate
    where candidate.user_position = 1
  )
  select
    ranked.entry_rank,
    ranked.player_name,
    ranked.score,
    ranked.accuracy,
    ranked.wpm,
    ranked.problems_solved,
    ranked.best_combo,
    ranked.survival_ms,
    ranked.created_at
  from ranked
  order by ranked.entry_rank
  limit p_limit;
end;
$$;

create or replace function public.get_today_ranking(
  p_content_version text,
  p_limit integer default 100
)
returns table (
  rank bigint,
  player_name text,
  score integer,
  accuracy numeric(5, 2),
  wpm numeric(6, 2),
  problems_solved smallint,
  best_combo smallint,
  survival_ms integer,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  utc_start timestamptz := date_trunc('day', now() at time zone 'UTC') at time zone 'UTC';
begin
  if p_limit is null or p_limit < 1 or p_limit > 100 then
    raise exception 'limit must be between 1 and 100' using errcode = '22023';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;

  return query
  with per_user as (
    select
      entry.*,
      row_number() over (
        partition by entry.user_id
        order by
          entry.score desc,
          entry.accuracy desc,
          entry.problems_solved desc,
          entry.best_combo desc,
          entry.wpm desc,
          entry.created_at asc,
          entry.id asc
      ) as user_position
    from public.ranking_entries as entry
    where entry.content_version = p_content_version
      and entry.game_mode = 'quick'
      and entry.created_at >= utc_start
      and entry.created_at < utc_start + interval '1 day'
  ),
  ranked as (
    select
      row_number() over (
        order by
          candidate.score desc,
          candidate.accuracy desc,
          candidate.problems_solved desc,
          candidate.best_combo desc,
          candidate.wpm desc,
          candidate.created_at asc,
          candidate.id asc
      ) as entry_rank,
      candidate.*
    from per_user as candidate
    where candidate.user_position = 1
  )
  select
    ranked.entry_rank,
    ranked.player_name,
    ranked.score,
    ranked.accuracy,
    ranked.wpm,
    ranked.problems_solved,
    ranked.best_combo,
    ranked.survival_ms,
    ranked.created_at
  from ranked
  order by ranked.entry_rank
  limit p_limit;
end;
$$;

create or replace function public.get_my_best(p_content_version text)
returns table (
  rank bigint,
  player_name text,
  score integer,
  accuracy numeric(5, 2),
  wpm numeric(6, 2),
  problems_solved smallint,
  best_combo smallint,
  survival_ms integer,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;

  return query
  with per_user as (
    select
      entry.*,
      row_number() over (
        partition by entry.user_id
        order by
          entry.score desc,
          entry.accuracy desc,
          entry.problems_solved desc,
          entry.best_combo desc,
          entry.wpm desc,
          entry.created_at asc,
          entry.id asc
      ) as user_position
    from public.ranking_entries as entry
    where entry.content_version = p_content_version
      and entry.game_mode = 'quick'
  ),
  ranked as (
    select
      row_number() over (
        order by
          candidate.score desc,
          candidate.accuracy desc,
          candidate.problems_solved desc,
          candidate.best_combo desc,
          candidate.wpm desc,
          candidate.created_at asc,
          candidate.id asc
      ) as entry_rank,
      candidate.*
    from per_user as candidate
    where candidate.user_position = 1
  )
  select
    ranked.entry_rank,
    ranked.player_name,
    ranked.score,
    ranked.accuracy,
    ranked.wpm,
    ranked.problems_solved,
    ranked.best_combo,
    ranked.survival_ms,
    ranked.created_at
  from ranked
  where ranked.user_id = auth.uid();
end;
$$;

create or replace function public.get_my_rank(
  p_session_id uuid,
  p_content_version text
)
returns table (
  rank bigint,
  player_name text,
  score integer,
  accuracy numeric(5, 2),
  wpm numeric(6, 2),
  problems_solved smallint,
  best_combo smallint,
  survival_ms integer,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_session_id is null then
    raise exception 'session id is required' using errcode = '22023';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;

  return query
  with target as (
    select entry.*
    from public.ranking_entries as entry
    where entry.user_id = auth.uid()
      and entry.session_id = p_session_id
      and entry.content_version = p_content_version
      and entry.game_mode = 'quick'
    limit 1
  ),
  other_user_runs as (
    select
      entry.*,
      row_number() over (
        partition by entry.user_id
        order by
          entry.score desc,
          entry.accuracy desc,
          entry.problems_solved desc,
          entry.best_combo desc,
          entry.wpm desc,
          entry.created_at asc,
          entry.id asc
      ) as user_position
    from public.ranking_entries as entry
    where entry.user_id <> auth.uid()
      and entry.content_version = p_content_version
      and entry.game_mode = 'quick'
  ),
  candidates as (
    select
      other.id,
      other.player_name,
      other.score,
      other.accuracy,
      other.wpm,
      other.problems_solved,
      other.best_combo,
      other.survival_ms,
      other.created_at,
      false as is_target
    from other_user_runs as other
    where other.user_position = 1
    union all
    select
      target.id,
      target.player_name,
      target.score,
      target.accuracy,
      target.wpm,
      target.problems_solved,
      target.best_combo,
      target.survival_ms,
      target.created_at,
      true as is_target
    from target
  ),
  ranked as (
    select
      row_number() over (
        order by
          candidate.score desc,
          candidate.accuracy desc,
          candidate.problems_solved desc,
          candidate.best_combo desc,
          candidate.wpm desc,
          candidate.created_at asc,
          candidate.id asc
      ) as entry_rank,
      candidate.*
    from candidates as candidate
  )
  select
    ranked.entry_rank,
    ranked.player_name,
    ranked.score,
    ranked.accuracy,
    ranked.wpm,
    ranked.problems_solved,
    ranked.best_combo,
    ranked.survival_ms,
    ranked.created_at
  from ranked
  where ranked.is_target;
end;
$$;

revoke all on function public.get_global_ranking(text, integer)
  from public, anon, authenticated;
revoke all on function public.get_today_ranking(text, integer)
  from public, anon, authenticated;
revoke all on function public.get_my_best(text)
  from public, anon, authenticated;
revoke all on function public.get_my_rank(uuid, text)
  from public, anon, authenticated;

grant execute on function public.get_global_ranking(text, integer) to anon, authenticated;
grant execute on function public.get_today_ranking(text, integer) to anon, authenticated;
grant execute on function public.get_my_best(text) to authenticated;
grant execute on function public.get_my_rank(uuid, text) to authenticated;

comment on table public.ranking_entries is
  'Minimal Quick Play leaderboard data. Client-computed scores are not cheat-proof.';
comment on function public.get_global_ranking(text, integer) is
  'Returns one best Quick Play run per user without user_id or session_id.';
comment on function public.get_today_ranking(text, integer) is
  'Returns UTC-today best Quick Play runs without user_id or session_id.';
comment on function public.get_my_best(text) is
  'Returns the authenticated user best Quick Play run and global rank.';
comment on function public.get_my_rank(uuid, text) is
  'Ranks an authenticated user owned session without exposing identifiers.';

commit;
