begin;

create table if not exists public.ranking_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid not null,
  player_name text not null,
  score integer not null,
  accuracy numeric(5, 2) not null,
  wpm numeric(6, 2) not null,
  problems_solved smallint not null,
  best_combo smallint not null,
  survival_ms integer not null,
  game_mode text not null,
  content_version text not null,
  client_version text not null,
  created_at timestamptz not null default now(),

  constraint ranking_entries_user_session_key unique (user_id, session_id),
  constraint ranking_entries_player_name_check
    check (player_name ~ '^[가-힣A-Za-z0-9_]{2,12}$'),
  constraint ranking_entries_score_check check (score between 0 and 10000000),
  constraint ranking_entries_accuracy_check check (accuracy between 0 and 100),
  constraint ranking_entries_wpm_check check (wpm between 0 and 250),
  constraint ranking_entries_problems_check check (problems_solved between 1 and 40),
  constraint ranking_entries_combo_check check (best_combo between 0 and 40),
  constraint ranking_entries_survival_check check (survival_ms between 10000 and 300000),
  constraint ranking_entries_mode_check check (game_mode = 'quick'),
  constraint ranking_entries_content_version_check
    check (
      char_length(content_version) between 1 and 20
      and content_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$'
    ),
  constraint ranking_entries_client_version_check
    check (
      char_length(client_version) between 1 and 20
      and client_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$'
    )
);

create index if not exists ranking_entries_global_idx
  on public.ranking_entries
  (
    content_version,
    game_mode,
    score desc,
    accuracy desc,
    problems_solved desc,
    best_combo desc,
    wpm desc,
    created_at asc
  );

create index if not exists ranking_entries_user_idx
  on public.ranking_entries
  (
    user_id,
    content_version,
    game_mode,
    score desc,
    accuracy desc,
    problems_solved desc,
    best_combo desc,
    wpm desc,
    created_at asc
  );

create index if not exists ranking_entries_today_idx
  on public.ranking_entries (created_at desc, content_version, game_mode);

alter table public.ranking_entries enable row level security;

drop policy if exists "Leaderboard is readable" on public.ranking_entries;
create policy "Leaderboard is readable"
on public.ranking_entries
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated anonymous users insert own runs"
  on public.ranking_entries;
create policy "Authenticated anonymous users insert own runs"
on public.ranking_entries
for insert
to authenticated
with check ((select auth.uid()) = user_id);

-- The browser has no raw-table SELECT privilege. Public reads go through the
-- narrow RPC return types below so user_id/session_id are never returned.
revoke all on table public.ranking_entries from public, anon, authenticated;
grant insert (
  user_id,
  session_id,
  player_name,
  score,
  accuracy,
  wpm,
  problems_solved,
  best_combo,
  survival_ms,
  game_mode,
  content_version,
  client_version
) on public.ranking_entries to authenticated;

-- created_at and id are intentionally omitted from the INSERT grant. They can
-- only be assigned by PostgreSQL, not backdated or chosen by a browser client.
revoke all on sequence public.ranking_entries_id_seq from public, anon, authenticated;
grant usage on sequence public.ranking_entries_id_seq to authenticated;

create table if not exists public.shared_question_revisions (
  id bigint generated by default as identity primary key,
  question_id text not null,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  content_version text not null,
  question jsonb not null,
  created_at timestamptz not null default now(),
  constraint shared_question_id_check
    check (question_id ~ '^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)*$'),
  constraint shared_question_version_check
    check (content_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$')
);

create index if not exists shared_question_latest_idx
  on public.shared_question_revisions (content_version, question_id, id desc);
create index if not exists shared_question_author_rate_idx
  on public.shared_question_revisions (author_user_id, created_at desc);

alter table public.shared_question_revisions enable row level security;
revoke all on table public.shared_question_revisions from public, anon, authenticated;
revoke all on sequence public.shared_question_revisions_id_seq from public, anon, authenticated;

create table if not exists public.online_players (
  user_id uuid primary key references auth.users(id) on delete cascade,
  player_name text not null,
  last_seen_at timestamptz not null default now(),
  constraint online_players_name_check
    check (player_name ~ '^[가-힣A-Za-z0-9_]{2,12}$')
);

create index if not exists online_players_seen_idx
  on public.online_players (last_seen_at desc);

alter table public.online_players enable row level security;
revoke all on table public.online_players from public, anon, authenticated;

create or replace function public.get_global_ranking(
  p_content_version text,
  p_limit integer default 100
)
returns table (
  rank bigint,
  player_name text,
  score integer,
  accuracy numeric(5, 2),
  wpm numeric(6, 2),
  problems_solved smallint,
  best_combo smallint,
  survival_ms integer,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if p_limit is null or p_limit < 1 or p_limit > 100 then
    raise exception 'limit must be between 1 and 100' using errcode = '22023';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;

  return query
  with per_user as (
    select
      entry.*,
      row_number() over (
        partition by entry.user_id
        order by
          entry.score desc,
          entry.accuracy desc,
          entry.problems_solved desc,
          entry.best_combo desc,
          entry.wpm desc,
          entry.created_at asc,
          entry.id asc
      ) as user_position
    from public.ranking_entries as entry
    where entry.content_version = p_content_version
      and entry.game_mode = 'quick'
  ),
  ranked as (
    select
      row_number() over (
        order by
          candidate.score desc,
          candidate.accuracy desc,
          candidate.problems_solved desc,
          candidate.best_combo desc,
          candidate.wpm desc,
          candidate.created_at asc,
          candidate.id asc
      ) as entry_rank,
      candidate.*
    from per_user as candidate
    where candidate.user_position = 1
  )
  select
    ranked.entry_rank,
    ranked.player_name,
    ranked.score,
    ranked.accuracy,
    ranked.wpm,
    ranked.problems_solved,
    ranked.best_combo,
    ranked.survival_ms,
    ranked.created_at
  from ranked
  order by ranked.entry_rank
  limit p_limit;
end;
$$;

create or replace function public.get_today_ranking(
  p_content_version text,
  p_limit integer default 100
)
returns table (
  rank bigint,
  player_name text,
  score integer,
  accuracy numeric(5, 2),
  wpm numeric(6, 2),
  problems_solved smallint,
  best_combo smallint,
  survival_ms integer,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  utc_start timestamptz := date_trunc('day', now() at time zone 'UTC') at time zone 'UTC';
begin
  if p_limit is null or p_limit < 1 or p_limit > 100 then
    raise exception 'limit must be between 1 and 100' using errcode = '22023';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;

  return query
  with per_user as (
    select
      entry.*,
      row_number() over (
        partition by entry.user_id
        order by
          entry.score desc,
          entry.accuracy desc,
          entry.problems_solved desc,
          entry.best_combo desc,
          entry.wpm desc,
          entry.created_at asc,
          entry.id asc
      ) as user_position
    from public.ranking_entries as entry
    where entry.content_version = p_content_version
      and entry.game_mode = 'quick'
      and entry.created_at >= utc_start
      and entry.created_at < utc_start + interval '1 day'
  ),
  ranked as (
    select
      row_number() over (
        order by
          candidate.score desc,
          candidate.accuracy desc,
          candidate.problems_solved desc,
          candidate.best_combo desc,
          candidate.wpm desc,
          candidate.created_at asc,
          candidate.id asc
      ) as entry_rank,
      candidate.*
    from per_user as candidate
    where candidate.user_position = 1
  )
  select
    ranked.entry_rank,
    ranked.player_name,
    ranked.score,
    ranked.accuracy,
    ranked.wpm,
    ranked.problems_solved,
    ranked.best_combo,
    ranked.survival_ms,
    ranked.created_at
  from ranked
  order by ranked.entry_rank
  limit p_limit;
end;
$$;

create or replace function public.get_my_best(p_content_version text)
returns table (
  rank bigint,
  player_name text,
  score integer,
  accuracy numeric(5, 2),
  wpm numeric(6, 2),
  problems_solved smallint,
  best_combo smallint,
  survival_ms integer,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;

  return query
  with per_user as (
    select
      entry.*,
      row_number() over (
        partition by entry.user_id
        order by
          entry.score desc,
          entry.accuracy desc,
          entry.problems_solved desc,
          entry.best_combo desc,
          entry.wpm desc,
          entry.created_at asc,
          entry.id asc
      ) as user_position
    from public.ranking_entries as entry
    where entry.content_version = p_content_version
      and entry.game_mode = 'quick'
  ),
  ranked as (
    select
      row_number() over (
        order by
          candidate.score desc,
          candidate.accuracy desc,
          candidate.problems_solved desc,
          candidate.best_combo desc,
          candidate.wpm desc,
          candidate.created_at asc,
          candidate.id asc
      ) as entry_rank,
      candidate.*
    from per_user as candidate
    where candidate.user_position = 1
  )
  select
    ranked.entry_rank,
    ranked.player_name,
    ranked.score,
    ranked.accuracy,
    ranked.wpm,
    ranked.problems_solved,
    ranked.best_combo,
    ranked.survival_ms,
    ranked.created_at
  from ranked
  where ranked.user_id = auth.uid();
end;
$$;

create or replace function public.get_my_rank(
  p_session_id uuid,
  p_content_version text
)
returns table (
  rank bigint,
  player_name text,
  score integer,
  accuracy numeric(5, 2),
  wpm numeric(6, 2),
  problems_solved smallint,
  best_combo smallint,
  survival_ms integer,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_session_id is null then
    raise exception 'session id is required' using errcode = '22023';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;

  return query
  with target as (
    select entry.*
    from public.ranking_entries as entry
    where entry.user_id = auth.uid()
      and entry.session_id = p_session_id
      and entry.content_version = p_content_version
      and entry.game_mode = 'quick'
    limit 1
  ),
  other_user_runs as (
    select
      entry.*,
      row_number() over (
        partition by entry.user_id
        order by
          entry.score desc,
          entry.accuracy desc,
          entry.problems_solved desc,
          entry.best_combo desc,
          entry.wpm desc,
          entry.created_at asc,
          entry.id asc
      ) as user_position
    from public.ranking_entries as entry
    where entry.user_id <> auth.uid()
      and entry.content_version = p_content_version
      and entry.game_mode = 'quick'
  ),
  candidates as (
    select
      other.id,
      other.player_name,
      other.score,
      other.accuracy,
      other.wpm,
      other.problems_solved,
      other.best_combo,
      other.survival_ms,
      other.created_at,
      false as is_target
    from other_user_runs as other
    where other.user_position = 1
    union all
    select
      target.id,
      target.player_name,
      target.score,
      target.accuracy,
      target.wpm,
      target.problems_solved,
      target.best_combo,
      target.survival_ms,
      target.created_at,
      true as is_target
    from target
  ),
  ranked as (
    select
      row_number() over (
        order by
          candidate.score desc,
          candidate.accuracy desc,
          candidate.problems_solved desc,
          candidate.best_combo desc,
          candidate.wpm desc,
          candidate.created_at asc,
          candidate.id asc
      ) as entry_rank,
      candidate.*
    from candidates as candidate
  )
  select
    ranked.entry_rank,
    ranked.player_name,
    ranked.score,
    ranked.accuracy,
    ranked.wpm,
    ranked.problems_solved,
    ranked.best_combo,
    ranked.survival_ms,
    ranked.created_at
  from ranked
  where ranked.is_target;
end;
$$;

create or replace function public.get_nearby_ranking(
  p_content_version text,
  p_radius integer default 5
)
returns table (
  rank bigint,
  player_name text,
  score integer,
  accuracy numeric(5, 2),
  wpm numeric(6, 2),
  problems_solved smallint,
  best_combo smallint,
  survival_ms integer,
  created_at timestamptz,
  is_current_user boolean
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_radius is null or p_radius < 1 or p_radius > 5 then
    raise exception 'radius must be between 1 and 5' using errcode = '22023';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;

  return query
  with per_user as (
    select entry.*,
      row_number() over (
        partition by entry.user_id
        order by entry.score desc, entry.accuracy desc, entry.problems_solved desc,
          entry.best_combo desc, entry.wpm desc, entry.created_at asc, entry.id asc
      ) as user_position
    from public.ranking_entries as entry
    where entry.content_version = p_content_version and entry.game_mode = 'quick'
  ), ranked as (
    select row_number() over (
        order by candidate.score desc, candidate.accuracy desc, candidate.problems_solved desc,
          candidate.best_combo desc, candidate.wpm desc, candidate.created_at asc, candidate.id asc
      ) as entry_rank,
      candidate.*
    from per_user as candidate
    where candidate.user_position = 1
  ), mine as (
    select ranked.entry_rank from ranked where ranked.user_id = auth.uid()
  )
  select ranked.entry_rank, ranked.player_name, ranked.score, ranked.accuracy, ranked.wpm,
    ranked.problems_solved, ranked.best_combo, ranked.survival_ms, ranked.created_at,
    ranked.user_id = auth.uid()
  from ranked cross join mine
  where ranked.entry_rank between greatest(1, mine.entry_rank - p_radius)
    and mine.entry_rank + p_radius
  order by ranked.entry_rank;
end;
$$;

create or replace function public.get_shared_questions(p_content_version text)
returns table (
  question_id text,
  level smallint,
  type text,
  skill text,
  difficulty smallint,
  code text,
  output text,
  output_mode text,
  answer text,
  accepted_answers jsonb,
  target_seconds smallint,
  tags jsonb,
  revision_id bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;
  return query
  with latest as (
    select distinct on (revision.question_id) revision.*
    from public.shared_question_revisions as revision
    where revision.content_version = p_content_version
    order by revision.question_id, revision.id desc
  )
  select latest.question_id,
    (latest.question->>'level')::smallint,
    latest.question->>'type', latest.question->>'skill',
    (latest.question->>'difficulty')::smallint,
    latest.question->>'code', latest.question->>'output', latest.question->>'outputMode',
    latest.question->>'answer', latest.question->'acceptedAnswers',
    (latest.question->>'targetSeconds')::smallint, latest.question->'tags', latest.id
  from latest order by latest.question_id limit 500;
end;
$$;

create or replace function public.submit_shared_question(
  p_content_version text,
  p_question jsonb,
  p_question_id text default null
)
returns table (question_id text, revision_id bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_question_id text;
  new_revision_id bigint;
  level_value integer;
  code_value text;
  answer_value text;
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;
  if p_question is null or jsonb_typeof(p_question) <> 'object'
     or p_question - array['level','type','skill','difficulty','code','output','outputMode',
       'answer','acceptedAnswers','targetSeconds','tags'] <> '{}'::jsonb then
    raise exception 'invalid question shape' using errcode = '22023';
  end if;
  if jsonb_typeof(p_question->'acceptedAnswers') <> 'array'
     or jsonb_array_length(p_question->'acceptedAnswers') > 5
     or jsonb_typeof(p_question->'tags') <> 'array'
     or jsonb_array_length(p_question->'tags') > 8 then
    raise exception 'invalid question arrays' using errcode = '22023';
  end if;
  if jsonb_typeof(p_question->'level') <> 'number'
     or jsonb_typeof(p_question->'difficulty') <> 'number'
     or jsonb_typeof(p_question->'targetSeconds') <> 'number'
     or jsonb_typeof(p_question->'type') <> 'string'
     or jsonb_typeof(p_question->'skill') <> 'string'
     or jsonb_typeof(p_question->'code') <> 'string'
     or jsonb_typeof(p_question->'output') <> 'string'
     or jsonb_typeof(p_question->'outputMode') <> 'string'
     or jsonb_typeof(p_question->'answer') <> 'string'
     or exists (
       select 1 from jsonb_array_elements(p_question->'acceptedAnswers') as item
       where jsonb_typeof(item) <> 'string' or char_length(item #>> '{}') not between 1 and 100
     )
     or exists (
       select 1 from jsonb_array_elements(p_question->'tags') as item
       where jsonb_typeof(item) <> 'string' or (item #>> '{}') !~ '^[a-z][a-z0-9-]*$'
     ) then
    raise exception 'invalid question field types' using errcode = '22023';
  end if;

  level_value := (p_question->>'level')::integer;
  code_value := p_question->>'code';
  answer_value := p_question->>'answer';
  if level_value not in (1, 2)
     or (level_value = 1 and p_question->>'type' <> 'copy')
     or (level_value = 2 and p_question->>'type' <> 'fill')
     or p_question->>'skill' not in ('print','variable','assignment','number','string','boolean',
       'arithmetic','comparison','if','elif','else','for','range','while','break','continue',
       'list','append','pop','sort','reverse','len','sum','min','max','random','shuffle')
     or (p_question->>'difficulty')::integer not between 1 and 3
     or (p_question->>'targetSeconds')::integer not between 5 and 15
     or p_question->>'outputMode' not in ('exact', 'example')
     or code_value is null or char_length(code_value) not between 1 and 300
     or answer_value is null
     or char_length(answer_value) not between 1 and (case when level_value = 2 then 30 else 100 end)
     or code_value ~ E'[\\r\\t]' or answer_value ~ E'[\\r\\n\\t]'
     or code_value ~ E'[ ]+(\\n|$)'
     or char_length(coalesce(p_question->>'output', '')) > 200
     or coalesce(p_question->>'output', '') ~ E'[\\r\\t]'
     or coalesce(p_question->>'output', '') ~ E'[ ]+(\\n|$)' then
    raise exception 'question values out of range' using errcode = '22023';
  end if;
  if (level_value = 1 and (answer_value <> code_value or coalesce(p_question->>'output', '') <> ''))
     or not ((p_question->'acceptedAnswers') ? answer_value)
     or (level_value = 1 and (
       jsonb_array_length(p_question->'acceptedAnswers') <> 1
       or p_question->'acceptedAnswers'->>0 <> answer_value
     ))
     or (level_value = 2 and (
       (char_length(code_value) - char_length(replace(code_value, '_____', ''))) / 5 <> 1
       or coalesce(p_question->>'output', '') = ''
     )) then
    raise exception 'level contract mismatch' using errcode = '22023';
  end if;
  if exists (
    select 1 from public.shared_question_revisions as recent
    where recent.author_user_id = auth.uid() and recent.created_at > now() - interval '5 seconds'
  ) then
    raise exception 'please wait before another edit' using errcode = '55000';
  end if;
  if p_question_id is not null and p_question_id !~ '^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)*$' then
    raise exception 'invalid question id' using errcode = '22023';
  end if;
  if p_question_id is null and (
    select count(distinct revision.question_id)
    from public.shared_question_revisions as revision
    where revision.content_version = p_content_version
  ) >= 500 then
    raise exception 'shared question limit reached' using errcode = '54000';
  end if;

  new_question_id := coalesce(p_question_id, 'community.' || gen_random_uuid()::text);
  insert into public.shared_question_revisions
    (question_id, author_user_id, content_version, question)
  values (new_question_id, auth.uid(), p_content_version, p_question)
  returning id into new_revision_id;
  return query select new_question_id, new_revision_id;
end;
$$;

create or replace function public.touch_online_player(p_player_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_player_name is null or p_player_name !~ '^[가-힣A-Za-z0-9_]{2,12}$' then
    raise exception 'invalid player name' using errcode = '22023';
  end if;
  insert into public.online_players (user_id, player_name, last_seen_at)
  values (auth.uid(), p_player_name, now())
  on conflict (user_id) do update
    set player_name = excluded.player_name, last_seen_at = excluded.last_seen_at;
end;
$$;

create or replace function public.get_online_players(
  p_content_version text,
  p_limit integer default 50
)
returns table (player_name text, best_score integer)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if p_limit is null or p_limit < 1 or p_limit > 50 then
    raise exception 'limit must be between 1 and 50' using errcode = '22023';
  end if;
  if p_content_version is null
     or p_content_version !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,19}$' then
    raise exception 'invalid content version' using errcode = '22023';
  end if;
  return query
  select online.player_name, coalesce(max(entry.score), 0)::integer
  from public.online_players as online
  left join public.ranking_entries as entry
    on entry.user_id = online.user_id
    and entry.content_version = p_content_version and entry.game_mode = 'quick'
  where online.last_seen_at >= now() - interval '90 seconds'
  group by online.user_id, online.player_name, online.last_seen_at
  order by coalesce(max(entry.score), 0) desc, online.last_seen_at desc
  limit p_limit;
end;
$$;

revoke all on function public.get_global_ranking(text, integer)
  from public, anon, authenticated;
revoke all on function public.get_today_ranking(text, integer)
  from public, anon, authenticated;
revoke all on function public.get_my_best(text)
  from public, anon, authenticated;
revoke all on function public.get_my_rank(uuid, text)
  from public, anon, authenticated;
revoke all on function public.get_nearby_ranking(text, integer)
  from public, anon, authenticated;
revoke all on function public.get_shared_questions(text)
  from public, anon, authenticated;
revoke all on function public.submit_shared_question(text, jsonb, text)
  from public, anon, authenticated;
revoke all on function public.touch_online_player(text)
  from public, anon, authenticated;
revoke all on function public.get_online_players(text, integer)
  from public, anon, authenticated;

grant execute on function public.get_global_ranking(text, integer) to anon, authenticated;
grant execute on function public.get_today_ranking(text, integer) to anon, authenticated;
grant execute on function public.get_my_best(text) to authenticated;
grant execute on function public.get_my_rank(uuid, text) to authenticated;
grant execute on function public.get_nearby_ranking(text, integer) to authenticated;
grant execute on function public.get_shared_questions(text) to anon, authenticated;
grant execute on function public.submit_shared_question(text, jsonb, text) to authenticated;
grant execute on function public.touch_online_player(text) to authenticated;
grant execute on function public.get_online_players(text, integer) to anon, authenticated;

comment on table public.ranking_entries is
  'Minimal Quick Play leaderboard data. Client-computed scores are not cheat-proof.';
comment on function public.get_global_ranking(text, integer) is
  'Returns one best Quick Play run per user without user_id or session_id.';
comment on function public.get_today_ranking(text, integer) is
  'Returns UTC-today best Quick Play runs without user_id or session_id.';
comment on function public.get_my_best(text) is
  'Returns the authenticated user best Quick Play run and global rank.';
comment on function public.get_my_rank(uuid, text) is
  'Ranks an authenticated user owned session without exposing identifiers.';
comment on function public.get_nearby_ranking(text, integer) is
  'Returns the authenticated user and up to five neighboring Quick ranks without identifiers.';
comment on table public.shared_question_revisions is
  'Append-only anonymous shared Practice question revisions; raw access is denied.';
comment on function public.submit_shared_question(text, jsonb, text) is
  'Validates and appends an anonymous shared Practice question revision without email or admin roles.';
comment on function public.get_online_players(text, integer) is
  'Returns recently active nicknames and Quick best scores without identifiers.';

commit;
